# Generated by Django 4.2.11 on 2024-06-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
